Minor fixes and cleanup
mt-mods/xcompat pull request #3
Opened 2024-02-26 08:16 UTC by OgelGames

2024-02-26 23:38 UTC, wsor4035 requested changes
.

2024-02-26 23:38 UTC, wsor4035 commented on .luacheckrc
> +	 "xcompat",
spacing

2024-02-26 23:38 UTC, wsor4035 commented on .luacheckrc
> +	"rp_sounds",
more spacing

2024-02-26 23:38 UTC, wsor4035 commented on README.md
> +# XCompat [xcompat]
redundant

2024-02-27 03:54 UTC, OgelGames commented on README.md
> +# XCompat [xcompat]
Yeah, I guess it is... 🤔

2024-02-27 06:18 UTC, BuckarooBanzay approved these changes

2024-02-27 06:28 UTC, merged